 /******************************************************************************
 *
 * Module: Port
 *
 * File Name: Port_PBcfg.c
 *
 * Description: Post Build Configuration Source file for TM4C123GH6PM Microcontroller - Port Driver
 *
 * Author: Ahmed Ibrahim
 ******************************************************************************/

#include "Port.h"

/* SoftWare Module Version */
#define PORT_PBCFG_SW_MAJOR_VERSION           (1U)
#define PORT_PBCFG_SW_MINOR_VERSION           (0U)
#define PORT_PBCFG_SW_PATCH_VERSION           (0U)

/*
 * AUTOSAR Version 4.0.3
 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION   (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION   (0U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION   (3U)


/* Check The Software Version between Port.h and Port_PBcfg.c */
#if ((PORT_SW_MAJOR_VERSION!=PORT_PBCFG_SW_MAJOR_VERSION)\
  || (PORT_SW_MINOR_VERSION!=PORT_PBCFG_SW_MINOR_VERSION)\
  || (PORT_SW_PATCH_VERSION!=PORT_PBCFG_SW_PATCH_VERSION))
   #error "The Software Version of Port_PBcfg.c doesn't match the version of Port.h driver"
#endif


/* Check The Autosar Version between Port.h and Port_PBcfg.c */
#if ((PORT_AR_RELEASE_MAJOR_VERSION!=PORT_PBCFG_AR_RELEASE_MAJOR_VERSION)\
  || (PORT_AR_RELEASE_MINOR_VERSION!=PORT_PBCFG_AR_RELEASE_MINOR_VERSION)\
  || (PORT_AR_RELEASE_PATCH_VERSION!=PORT_PBCFG_AR_RELEASE_PATCH_VERSION))
   #error "The Autosar Version of Port_PBcfg.c doesn't match the version of Port.h driver"
#endif
   /* Configuration Structure :                              *
    *                          1-Direction                   *
    *                          2-Internal Resistor           *
    *                          3-Level Value(Initial value)  *
    *                          4-PORT ID                     *
    *                          5-PIN ID                      *
    *                          6-Pin Initial Mode            *
    *                          7-Pin Direction Changeability *
    *                          8-Pin Mode Changeability      */ 
  const Port_ConfigType Port_Configuration={
     PORTA_PIN0_DIRECTION,PULL_UP,PORTA_PIN0_LEVEL_VALUE,PORTA_ID,PORTA_PIN0_ID,PORTA_PIN0_INITIAL_MODE,PORTA_PIN0_DIRECTION_CHANGEABLE,PORTA_PIN0_MODE_CHANGEABLE,
     PORTA_PIN1_DIRECTION,PULL_UP,PORTA_PIN1_LEVEL_VALUE,PORTA_ID,PORTA_PIN1_ID,PORTA_PIN1_INITIAL_MODE,PORTA_PIN1_DIRECTION_CHANGEABLE,PORTA_PIN1_MODE_CHANGEABLE,
     PORTA_PIN2_DIRECTION,PULL_UP,PORTA_PIN2_LEVEL_VALUE,PORTA_ID,PORTA_PIN2_ID,PORTA_PIN2_INITIAL_MODE,PORTA_PIN2_DIRECTION_CHANGEABLE,PORTA_PIN2_MODE_CHANGEABLE,
     PORTA_PIN3_DIRECTION,PULL_UP,PORTA_PIN3_LEVEL_VALUE,PORTA_ID,PORTA_PIN3_ID,PORTA_PIN3_INITIAL_MODE,PORTA_PIN3_DIRECTION_CHANGEABLE,PORTA_PIN3_MODE_CHANGEABLE,
     PORTA_PIN4_DIRECTION,PULL_UP,PORTA_PIN4_LEVEL_VALUE,PORTA_ID,PORTA_PIN4_ID,PORTA_PIN4_INITIAL_MODE,PORTA_PIN4_DIRECTION_CHANGEABLE,PORTA_PIN4_MODE_CHANGEABLE,
     PORTA_PIN5_DIRECTION,PULL_UP,PORTA_PIN5_LEVEL_VALUE,PORTA_ID,PORTA_PIN5_ID,PORTA_PIN5_INITIAL_MODE,PORTA_PIN5_DIRECTION_CHANGEABLE,PORTA_PIN5_MODE_CHANGEABLE,
     PORTA_PIN6_DIRECTION,PULL_UP,PORTA_PIN6_LEVEL_VALUE,PORTA_ID,PORTA_PIN6_ID,PORTA_PIN6_INITIAL_MODE,PORTA_PIN6_DIRECTION_CHANGEABLE,PORTA_PIN6_MODE_CHANGEABLE,
     PORTA_PIN7_DIRECTION,PULL_UP,PORTA_PIN7_LEVEL_VALUE,PORTA_ID,PORTA_PIN7_ID,PORTA_PIN7_INITIAL_MODE,PORTA_PIN7_DIRECTION_CHANGEABLE,PORTA_PIN7_MODE_CHANGEABLE,
     PORTB_PIN0_DIRECTION,PULL_UP,PORTB_PIN0_LEVEL_VALUE,PORTB_ID,PORTB_PIN0_ID,PORTB_PIN0_INITIAL_MODE,PORTB_PIN0_DIRECTION_CHANGEABLE,PORTB_PIN0_MODE_CHANGEABLE,
     PORTB_PIN1_DIRECTION,PULL_UP,PORTB_PIN1_LEVEL_VALUE,PORTB_ID,PORTB_PIN1_ID,PORTB_PIN1_INITIAL_MODE,PORTB_PIN1_DIRECTION_CHANGEABLE,PORTB_PIN1_MODE_CHANGEABLE,
     PORTB_PIN2_DIRECTION,PULL_UP,PORTB_PIN2_LEVEL_VALUE,PORTB_ID,PORTB_PIN2_ID,PORTB_PIN2_INITIAL_MODE,PORTB_PIN2_DIRECTION_CHANGEABLE,PORTB_PIN2_MODE_CHANGEABLE,
     PORTB_PIN3_DIRECTION,PULL_UP,PORTB_PIN3_LEVEL_VALUE,PORTB_ID,PORTB_PIN3_ID,PORTB_PIN3_INITIAL_MODE,PORTB_PIN3_DIRECTION_CHANGEABLE,PORTB_PIN3_MODE_CHANGEABLE,
     PORTB_PIN4_DIRECTION,PULL_UP,PORTB_PIN4_LEVEL_VALUE,PORTB_ID,PORTB_PIN4_ID,PORTB_PIN4_INITIAL_MODE,PORTB_PIN4_DIRECTION_CHANGEABLE,PORTB_PIN4_MODE_CHANGEABLE,
     PORTB_PIN5_DIRECTION,PULL_UP,PORTB_PIN5_LEVEL_VALUE,PORTB_ID,PORTB_PIN5_ID,PORTB_PIN5_INITIAL_MODE,PORTB_PIN5_DIRECTION_CHANGEABLE,PORTB_PIN5_MODE_CHANGEABLE,
     PORTB_PIN6_DIRECTION,PULL_UP,PORTB_PIN6_LEVEL_VALUE,PORTB_ID,PORTB_PIN6_ID,PORTB_PIN6_INITIAL_MODE,PORTB_PIN6_DIRECTION_CHANGEABLE,PORTB_PIN6_MODE_CHANGEABLE,
     PORTB_PIN7_DIRECTION,PULL_UP,PORTB_PIN7_LEVEL_VALUE,PORTB_ID,PORTB_PIN7_ID,PORTB_PIN7_INITIAL_MODE,PORTB_PIN7_DIRECTION_CHANGEABLE,PORTB_PIN7_MODE_CHANGEABLE,
     PORTC_PIN0_DIRECTION,PULL_UP,PORTC_PIN0_LEVEL_VALUE,PORTC_ID,PORTC_PIN0_ID,PORTC_PIN0_INITIAL_MODE,PORTC_PIN0_DIRECTION_CHANGEABLE,PORTC_PIN0_MODE_CHANGEABLE,
     PORTC_PIN1_DIRECTION,PULL_UP,PORTC_PIN1_LEVEL_VALUE,PORTC_ID,PORTC_PIN1_ID,PORTC_PIN1_INITIAL_MODE,PORTC_PIN1_DIRECTION_CHANGEABLE,PORTC_PIN1_MODE_CHANGEABLE,
     PORTC_PIN2_DIRECTION,PULL_UP,PORTC_PIN2_LEVEL_VALUE,PORTC_ID,PORTC_PIN2_ID,PORTC_PIN2_INITIAL_MODE,PORTC_PIN2_DIRECTION_CHANGEABLE,PORTC_PIN2_MODE_CHANGEABLE,
     PORTC_PIN3_DIRECTION,PULL_UP,PORTC_PIN3_LEVEL_VALUE,PORTC_ID,PORTC_PIN3_ID,PORTC_PIN3_INITIAL_MODE,PORTC_PIN3_DIRECTION_CHANGEABLE,PORTC_PIN3_MODE_CHANGEABLE,
     PORTC_PIN4_DIRECTION,PULL_UP,PORTC_PIN4_LEVEL_VALUE,PORTC_ID,PORTC_PIN4_ID,PORTC_PIN4_INITIAL_MODE,PORTC_PIN4_DIRECTION_CHANGEABLE,PORTC_PIN4_MODE_CHANGEABLE,
     PORTC_PIN5_DIRECTION,PULL_UP,PORTC_PIN5_LEVEL_VALUE,PORTC_ID,PORTC_PIN5_ID,PORTC_PIN5_INITIAL_MODE,PORTC_PIN5_DIRECTION_CHANGEABLE,PORTC_PIN5_MODE_CHANGEABLE,
     PORTC_PIN6_DIRECTION,PULL_UP,PORTC_PIN6_LEVEL_VALUE,PORTC_ID,PORTC_PIN6_ID,PORTC_PIN6_INITIAL_MODE,PORTC_PIN6_DIRECTION_CHANGEABLE,PORTC_PIN6_MODE_CHANGEABLE,
     PORTC_PIN7_DIRECTION,PULL_UP,PORTC_PIN7_LEVEL_VALUE,PORTC_ID,PORTC_PIN7_ID,PORTC_PIN7_INITIAL_MODE,PORTC_PIN7_DIRECTION_CHANGEABLE,PORTC_PIN7_MODE_CHANGEABLE,
     PORTD_PIN0_DIRECTION,PULL_UP,PORTD_PIN0_LEVEL_VALUE,PORTD_ID,PORTD_PIN0_ID,PORTD_PIN0_INITIAL_MODE,PORTD_PIN0_DIRECTION_CHANGEABLE,PORTD_PIN0_MODE_CHANGEABLE,
     PORTD_PIN1_DIRECTION,PULL_UP,PORTD_PIN1_LEVEL_VALUE,PORTD_ID,PORTD_PIN1_ID,PORTD_PIN1_INITIAL_MODE,PORTD_PIN1_DIRECTION_CHANGEABLE,PORTD_PIN1_MODE_CHANGEABLE,
     PORTD_PIN2_DIRECTION,PULL_UP,PORTD_PIN2_LEVEL_VALUE,PORTD_ID,PORTD_PIN2_ID,PORTD_PIN2_INITIAL_MODE,PORTD_PIN2_DIRECTION_CHANGEABLE,PORTD_PIN2_MODE_CHANGEABLE,
     PORTD_PIN3_DIRECTION,PULL_UP,PORTD_PIN3_LEVEL_VALUE,PORTD_ID,PORTD_PIN3_ID,PORTD_PIN3_INITIAL_MODE,PORTD_PIN3_DIRECTION_CHANGEABLE,PORTD_PIN3_MODE_CHANGEABLE,
     PORTD_PIN4_DIRECTION,PULL_UP,PORTD_PIN4_LEVEL_VALUE,PORTD_ID,PORTD_PIN4_ID,PORTD_PIN4_INITIAL_MODE,PORTD_PIN4_DIRECTION_CHANGEABLE,PORTD_PIN4_MODE_CHANGEABLE,
     PORTD_PIN5_DIRECTION,PULL_UP,PORTD_PIN5_LEVEL_VALUE,PORTD_ID,PORTD_PIN5_ID,PORTD_PIN5_INITIAL_MODE,PORTD_PIN5_DIRECTION_CHANGEABLE,PORTD_PIN5_MODE_CHANGEABLE,
     PORTD_PIN6_DIRECTION,PULL_UP,PORTD_PIN6_LEVEL_VALUE,PORTD_ID,PORTD_PIN6_ID,PORTD_PIN6_INITIAL_MODE,PORTD_PIN6_DIRECTION_CHANGEABLE,PORTD_PIN6_MODE_CHANGEABLE,
     PORTD_PIN7_DIRECTION,PULL_UP,PORTD_PIN7_LEVEL_VALUE,PORTD_ID,PORTD_PIN7_ID,PORTD_PIN7_INITIAL_MODE,PORTD_PIN7_DIRECTION_CHANGEABLE,PORTD_PIN7_MODE_CHANGEABLE,
     PORTE_PIN0_DIRECTION,PULL_UP,PORTE_PIN0_LEVEL_VALUE,PORTE_ID,PORTE_PIN0_ID,PORTE_PIN0_INITIAL_MODE,PORTE_PIN0_DIRECTION_CHANGEABLE,PORTE_PIN0_MODE_CHANGEABLE,
     PORTE_PIN1_DIRECTION,PULL_UP,PORTE_PIN1_LEVEL_VALUE,PORTE_ID,PORTE_PIN1_ID,PORTE_PIN1_INITIAL_MODE,PORTE_PIN1_DIRECTION_CHANGEABLE,PORTE_PIN1_MODE_CHANGEABLE,
     PORTE_PIN2_DIRECTION,PULL_UP,PORTE_PIN2_LEVEL_VALUE,PORTE_ID,PORTE_PIN2_ID,PORTE_PIN2_INITIAL_MODE,PORTE_PIN2_DIRECTION_CHANGEABLE,PORTE_PIN2_MODE_CHANGEABLE,
     PORTE_PIN3_DIRECTION,PULL_UP,PORTE_PIN3_LEVEL_VALUE,PORTE_ID,PORTE_PIN3_ID,PORTE_PIN3_INITIAL_MODE,PORTE_PIN3_DIRECTION_CHANGEABLE,PORTE_PIN3_MODE_CHANGEABLE,
     PORTE_PIN4_DIRECTION,PULL_UP,PORTE_PIN4_LEVEL_VALUE,PORTE_ID,PORTE_PIN4_ID,PORTE_PIN4_INITIAL_MODE,PORTE_PIN4_DIRECTION_CHANGEABLE,PORTE_PIN4_MODE_CHANGEABLE,
     PORTE_PIN5_DIRECTION,PULL_UP,PORTE_PIN5_LEVEL_VALUE,PORTE_ID,PORTE_PIN5_ID,PORTE_PIN5_INITIAL_MODE,PORTE_PIN5_DIRECTION_CHANGEABLE,PORTE_PIN5_MODE_CHANGEABLE,
     PORTF_PIN0_DIRECTION,PULL_UP,PORTF_PIN0_LEVEL_VALUE,PORTF_ID,PORTF_PIN0_ID,PORTF_PIN0_INITIAL_MODE,PORTF_PIN0_DIRECTION_CHANGEABLE,PORTF_PIN0_MODE_CHANGEABLE,
     PORTF_PIN1_DIRECTION,PULL_UP,PORTF_PIN1_LEVEL_VALUE,PORTF_ID,PORTF_PIN1_ID,PORTF_PIN1_INITIAL_MODE,PORTF_PIN1_DIRECTION_CHANGEABLE,PORTF_PIN1_MODE_CHANGEABLE,
     PORTF_PIN2_DIRECTION,PULL_UP,PORTF_PIN2_LEVEL_VALUE,PORTF_ID,PORTF_PIN2_ID,PORTF_PIN2_INITIAL_MODE,PORTF_PIN2_DIRECTION_CHANGEABLE,PORTF_PIN2_MODE_CHANGEABLE,
     PORTF_PIN3_DIRECTION,PULL_UP,PORTF_PIN3_LEVEL_VALUE,PORTF_ID,PORTF_PIN3_ID,PORTF_PIN3_INITIAL_MODE,PORTF_PIN3_DIRECTION_CHANGEABLE,PORTF_PIN3_MODE_CHANGEABLE,
     PORTF_PIN4_DIRECTION,PULL_UP,PORTF_PIN4_LEVEL_VALUE,PORTF_ID,PORTF_PIN4_ID,PORTF_PIN4_INITIAL_MODE,PORTF_PIN4_DIRECTION_CHANGEABLE,PORTF_PIN4_MODE_CHANGEABLE};
